### ISSUE TITLE
doesn't work with reuseaddr

### ISSUE THREAD

**Issue by stevenvachon** [joeferner/node-openport#3]
Node uses reuseaddr by default.

Let's say you started a node server on port 8080 then, in another node instance were to check if 8080 was available, it'd pass the test, resulting in a fatal error.

**Comment by joeferner** [comment]
Looks like close is async and the callback was being called before close was complete.

https://github.com/joeferner/node-openport/commit/9b8280eade98e99108615f0df77d4a0f1343c40e
