### ISSUE TITLE
Found an open port that didn't work

### ISSUE THREAD

**Issue by esend7881** [joeferner/node-openport#4]
I kept finding open ports that didn't actually work when I used them and I found out what fixed the issue:

In the `createServer` function I altered the `listen` call to be:

		  server.listen(port, 'localhost', 1, function () {
		    server.close();
		    callback(null, port);
		  });

By ensuring a backlog of 1 and specifying localhost, my issues went away. I'm not sure if this is worth committing the actual code, as my code is specific to `localhost` but I wonder if it will help others.

PS. I don't know for sure why this works

**Comment by joeferner** [comment]
I'm guessing by default listen binds to any address (0.0.0.0) which uses a different set of ports than local host. If you don't specify a backlog does it still work? I might need to add an optional argument for which address to use.

**Comment by esend7881** [comment]
Yeah, when I take out the `backlog` parameter, it still works. so my code now looks like:

			createServer : function(port, callback) {
				  var server = require('net').createServer();
				  server.on('error', function () {
				    callback(null, false);
				  });
				  server.listen(port, 'localhost', function () {
				    server.close();
				    callback(null, port);
				  });
			}},

**Comment by joeferner** [comment]
Looks like close is async and the callback was being called before close was complete.

https://github.com/joeferner/node-openport/commit/9b8280eade98e99108615f0df77d4a0f1343c40e
